  name: Email notification flow
  run-name: ${{ github.actor }} is running a ${{ github.event_name }}
  on:
    push:
      branches:
        - main
        - develop
  jobs:
    checkout:
      name: Checkout
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
    info:
      name: Info
      runs-on: ubuntu-latest
      needs: checkout
      steps:
        - name: Print info
          run: |
            ls ${{ github.workspace }}
        - name: Print repo url
          run: echo "${{ github.repositoryUrl }}"
        - name: Print runner
          run: echo "${{ runner.arch }} - ${{ runner.os }} - ${{ runner.os }} - ${{ runner.temp }}"
    secrets:
      name: Secrets
      runs-on: ubuntu-latest
      needs: info
      steps:
        - name: Print secrets
          run: echo "${{ secrets.ACTIONS_SECRET }}"
        - name: Print variables
          run: echo "${{ vars.ACTIONS_VARIABLE }}"
        - name: Print env vars
          run: echo "${{ env.ACTIONS_SECRET }}"
