name: "Build App"
run-name: ${{ github.actor }} is running a ${{ github.event_name }}
on: [push]
jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # with:
        #   ref: '2727d8719b713e23fb014cbaa6ce0ede7b60affc'
      - name: Print Commit SHA
        run: |
          echo "Commit SHA: $GITHUB_SHA"
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: "Java version"
        run: echo "java -version"
      - name: Build with Maven
        run: mvn -B clean package --file pom.xml
      - name: Print info workspace
        run: |
          ls ${{ github.workspace }}
      - name: Print info target
        run: |
          ls ./target
      - uses: actions/upload-artifact@v3
        with:
          name: gh-act
          path: ./target/gh-act*.jar
  lint:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: "Java version"
        run: echo "java -version"
      - name: Build with Maven
        run: |
          mvn -B clean package --file pom.xml
      - name: Checkstyle Maven
        run: |
          mvn checkstyle:check --file.pom.xml
      - name: Print info workspace
        run: |
          ls ${{ github.workspace }}
      - name: Print info target
        run: |
          ls ./target
      
