name: "Build App"
run-name: ${{ github.actor }} is running a ${{ github.event_name }}
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Print commit sha
        run: echo $
